name: Scrape
on:
  schedule:
    - cron: '0 15 * * *'


jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run the scraper
        run: python populate_stats.py

      - name: Commit and push changes to stats.csv
        run: |
          git config --global user.name "Scraper Bot"
          git config --global user.email "gagarwal003@gmail.com"
          
          git add stats.csv
          
          # Check if there are changes to commit
          git commit -m "Scraped movies" || echo "No changes to commit"
          
          git push
