name: Test Hello World

on:
  schedule:
    - cron: "* * * * *"  # Runs every minute

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Run Hello World
      run: echo "Hello, World!"
