name: Test Hello World

on:
  schedule:
    - cron: "* * * * *"  # Runs every minute
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Run Hello World
      run: echo "Hello, World!"
